export { addComputedTypes } from './addComputedTypes'
export { getComputedQuickInfoAtPosition } from './getComputedQuickInfoAtPosition'
export {
  getTypeDocumentation,
  type DocumentationMetadata,
  type SharedMetadata,
  type ParameterMetadata,
  type PropertyMetadata,
  type PropertyFilter,
  type PropertiesMetadata,
  type SharedValueMetadata,
  type FunctionValueMetadata,
  type ObjectValueMetadata,
  type LiteralValueMetadata,
  type ValueMetadata,
  type InterfaceMetadata,
  type TypeAliasMetadata,
  type EnumMetadata,
  type SharedClassMemberMetadata,
  type ClassMetadata,
  type ClassAccessorMetadata,
  type ClassGetAccessorMetadata,
  type ClassSetAccessorMetadata,
  type ClassPropertyMetadata,
  type ClassMethodMetadata,
  type FunctionMetadata,
  type ComponentMetadata,
  type UnknownMetadata,
  type MetadataMap,
  type MetadataOfKind,
} from './getTypeDocumentation'
