export { addComputedTypes } from './addComputedTypes'
export { getComputedQuickInfoAtPosition } from './getComputedQuickInfoAtPosition'
export {
  getTypeDocumentation,
  type DocumentationMetadata,
  type SharedMetadata,
  type ParameterMetadata,
  type PropertyMetadata,
  type PropertyFilter,
  type SharedValueMetadata,
  type FunctionValueMetadata,
  type ObjectValueMetadata,
  type ValueMetadata,
  type InterfaceMetadata,
  type TypeAliasMetadata,
  type EnumMetadata,
  type SharedClassMemberMetadata,
  type ClassMetadata,
  type ClassAccessorMetadata,
  type ClassGetAccessorMetadata,
  type ClassSetAccessorMetadata,
  type ClassPropertyMetadata,
  type ClassMethodMetadata,
  type FunctionMetadata,
  type ComponentMetadata,
} from './getTypeDocumentation'
